// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/menta2l/valhalla-layout/internal/data/ent/migrate"

	"github.com/menta2l/valhalla-layout/internal/data/ent/hello"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Hello is the client for interacting with the Hello builders.
	Hello *HelloClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Hello = NewHelloClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Hello:  NewHelloClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Hello:  NewHelloClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Hello.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Hello.Use(hooks...)
}

// HelloClient is a client for the Hello schema.
type HelloClient struct {
	config
}

// NewHelloClient returns a client for the Hello from the given config.
func NewHelloClient(c config) *HelloClient {
	return &HelloClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `hello.Hooks(f(g(h())))`.
func (c *HelloClient) Use(hooks ...Hook) {
	c.hooks.Hello = append(c.hooks.Hello, hooks...)
}

// Create returns a create builder for Hello.
func (c *HelloClient) Create() *HelloCreate {
	mutation := newHelloMutation(c.config, OpCreate)
	return &HelloCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Hello entities.
func (c *HelloClient) CreateBulk(builders ...*HelloCreate) *HelloCreateBulk {
	return &HelloCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Hello.
func (c *HelloClient) Update() *HelloUpdate {
	mutation := newHelloMutation(c.config, OpUpdate)
	return &HelloUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *HelloClient) UpdateOne(h *Hello) *HelloUpdateOne {
	mutation := newHelloMutation(c.config, OpUpdateOne, withHello(h))
	return &HelloUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *HelloClient) UpdateOneID(id int) *HelloUpdateOne {
	mutation := newHelloMutation(c.config, OpUpdateOne, withHelloID(id))
	return &HelloUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Hello.
func (c *HelloClient) Delete() *HelloDelete {
	mutation := newHelloMutation(c.config, OpDelete)
	return &HelloDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *HelloClient) DeleteOne(h *Hello) *HelloDeleteOne {
	return c.DeleteOneID(h.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *HelloClient) DeleteOneID(id int) *HelloDeleteOne {
	builder := c.Delete().Where(hello.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &HelloDeleteOne{builder}
}

// Query returns a query builder for Hello.
func (c *HelloClient) Query() *HelloQuery {
	return &HelloQuery{
		config: c.config,
	}
}

// Get returns a Hello entity by its id.
func (c *HelloClient) Get(ctx context.Context, id int) (*Hello, error) {
	return c.Query().Where(hello.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *HelloClient) GetX(ctx context.Context, id int) *Hello {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *HelloClient) Hooks() []Hook {
	return c.hooks.Hello
}
