// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HellosColumns holds the columns for the "hellos" table.
	HellosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// HellosTable holds the schema information for the "hellos" table.
	HellosTable = &schema.Table{
		Name:       "hellos",
		Columns:    HellosColumns,
		PrimaryKey: []*schema.Column{HellosColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HellosTable,
	}
)

func init() {
}
